
tasks:
  run-test:
    steps:
    - checkout
    - cache/pull:
        key: npm-cache-{{ checksum "package-lock.json" }}
    - run:  npm ci
    - cache/push:
        key: npm-cache-{{ checksum "package-lock.json" }}
        paths:
        - node_modules
    - run: npm test